### PR TITLE
Added USBasp instructions

### PR DESCRIPTION
**Pull request by PatrickSteiner**
Based on my struggle with flashing the Arduino, I would like to propose a small addition to the documentation.

### CODE REVIEW

**Comment by RealNobser** [comment]
The upload command is missing the fuse settings. Is that intentional? Doesn't the USBasp support setting fuses?

**Comment by PatrickSteiner** [comment]
you are right, I added them now. I was able to flash the firmware also without setting the fuse and the Arduino started with "MarcDuino Dome Master" in Stdout. So not sure what effect the fuses have ... am not experienced in coding so close to the hardware level.

**Comment by PatrickSteiner** [comment]
Also changed the current upload command in platformio.ini, as you did define the env-variables for the fuses but than used hardcoded values in the command.

**Comment by PatrickSteiner** [comment]
Also added a new section to the documentation on assigning roles to MarcDuinos. I only learned about this step as I wondered how the MarcDuinos would know what they are and did ask Ben. He pointed me to the needed setup commands. 

As a user I felt it better to get this information "pushed into my face" and not be hidden in a table.

Please feel free to use this additional text, or not!

**Pull request merged**
